# Generated by Django 4.1.6 on 2023-02-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbasicdetails",
            name="salary",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
