# Generated by Django 4.1.6 on 2023-02-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_useradditionaldetail_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousorganisationdetail',
            name='experience_in_years',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='previousorganisationdetail',
            name='previous_organisation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='previousorganisationdetail',
            name='previous_organisation_designation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
