# Generated by Django 4.1.6 on 2023-02-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_userdocument_doc_file_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbankdetail",
            name="branch_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
