# Generated by Django 4.1.6 on 2023-02-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_userbankdetail_branch_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teams",
            name="is_completed_teams",
        ),
        migrations.AddField(
            model_name="teams",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
