# Generated by Django 4.1.5 on 2023-01-27 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_month_ctc', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('house_rent_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pf_employer', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pf_employee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('profession_tax', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('epf_employer', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('eps_employer', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ot_pay', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('emp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_users', to=settings.AUTH_USER_MODEL)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_months', to='payroll.month')),
            ],
        ),
        migrations.CreateModel(
            name='MonthAttendanceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('absent_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('week_offs', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('paid_leaves', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('non_paid_leaves', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('paid_holiday', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('sand_witched_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('total_paid_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('over_time_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_attendance_counter_user', to=settings.AUTH_USER_MODEL)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_attendance_counter_month', to='payroll.month')),
            ],
        ),
        migrations.CreateModel(
            name='MissingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('description', models.TextField(default='Attendance disappeared for some reason')),
                ('is_half_day', models.BooleanField(default=False)),
                ('is_first_half', models.BooleanField(default=False)),
                ('is_second_half', models.BooleanField(default=False)),
                ('is_requested', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance_approved_by', to=settings.AUTH_USER_MODEL)),
                ('emp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_attendance_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_count', models.IntegerField(default=0)),
                ('pl_count', models.IntegerField(default=0)),
                ('cl_count', models.IntegerField(default=0)),
                ('lop_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_count_users', to=settings.AUTH_USER_MODEL)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_count_month', to='payroll.month')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_apply', models.DateField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('no_of_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('type', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=255)),
                ('attachment_doc', models.FileField(null=True, upload_to='leave_docs')),
                ('is_approved', models.BooleanField(default=False)),
                ('start_date_is_half', models.BooleanField(default=False)),
                ('start_date_is_first_half', models.BooleanField(default=False)),
                ('start_date_is_second_half', models.BooleanField(default=False)),
                ('is_requested', models.BooleanField(default=True)),
                ('end_date_is_half', models.BooleanField(default=False)),
                ('end_date_is_first_half', models.BooleanField(default=False)),
                ('end_date_is_second_half', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_application_approved_by', to=settings.AUTH_USER_MODEL)),
                ('emp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_application_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holiday_month', to='payroll.month')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_is_half', models.BooleanField(default=False)),
                ('date_is_first_half', models.BooleanField(default=False)),
                ('date_is_second_half', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_leave_users', to=settings.AUTH_USER_MODEL)),
                ('leave_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_leave_users', to='payroll.leaveapplication')),
            ],
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('login_time', models.TimeField(auto_now_add=True)),
                ('logout_time', models.TimeField(null=True)),
                ('working_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_half_day', models.BooleanField(default=False)),
                ('is_first_half', models.BooleanField(default=False)),
                ('is_second_half', models.BooleanField(default=False)),
                ('is_requested', models.BooleanField(default=False)),
                ('is_present', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_attend_approved_by', to=settings.AUTH_USER_MODEL)),
                ('emp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance_user', to=settings.AUTH_USER_MODEL)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance_month', to='payroll.month')),
            ],
        ),
    ]
