# Generated by Django 4.1.5 on 2023-01-31 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='medical_allowance',
            new_name='conveyance_allowance',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='other_allowance',
            new_name='utility_allowance',
        ),
    ]
