# Generated by Django 4.1.6 on 2023-02-09 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0002_rename_medical_allowance_salary_conveyance_allowance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingattendance',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='missingattendance',
            name='date',
            field=models.DateField(),
        ),
    ]
